#!/usr/bin/env python

"""send KeyboardComposer a fade request, for use from the shell"""

import sys,xmlrpclib

subname = sys.argv[1]
level = float(sys.argv[2])
fadesecs = 0
if len(sys.argv)>3:
    fadesecs = float(sys.argv[3])

levelserver = xmlrpclib.ServerProxy("http://localhost:8050")

levelserver.fadesub(subname,level,fadesecs)


