#!/usr/bin/env python

import sys
from CueFaders import CueList, Cue

cuelist = CueList('cues/dolly')

for line in sys.stdin.readlines():
    line = line.strip()
    if not line:
        continue
    page, name = line.split(' ', 1)
    print page, '|', name
    newcue = Cue(name)
    newcue.page = page
    cuelist.add_cue(newcue)
